- 👋 I’m @IBBN444
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
IBBN444/IBBN444 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
adb shell pm grant com.tribalfs.pixels android.permission.WRITE_SECURE_SETTINGS'
